name: 脚本运行并推送到目标仓库

on:
  push:
    branches:
      - main  

jobs:
  run-python-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: 克隆当前仓库
      uses: actions/checkout@v3

    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' 

    - name: 安装依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y libjpeg-dev zlib1g-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 运行 Python 脚本
      run: |
        python lens.py

    - name: 克隆目标仓库
      uses: actions/checkout@v3
      with:
        repository: ${{ secrets.REPO }}  
        path: target-repo
        token: ${{ secrets.TOKEN }}  

    - name: 判断目标仓库是否存在
      run: |
        if [ ! -d "target-repo/.git" ]; then
          echo "Error: Target repository not cloned or .git directory missing"
          exit 1
        fi
  
    - name: 清空目标仓库
      run: |
        cd target-repo
        find . ! -path './.git*' ! -path '.' -exec rm -rf {} +

    - name: 将生成的文件复制到目标仓库
      run: |
        cp -r output/*  target-repo/  

    - name: 提交并推送更改到目标仓库
      run: |
        cd target-repo
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add -f .
        git commit -m "Automated commit by GitHub Actions"
        git push